on:
  push:
    branches: [ master, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Test PostgreSQL
        run: ./gradlew test --no-daemon
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql:postgres
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: secret
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Duser.language=ja"
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Install Graphviz
        run: |
          sudo apt update
          sudo apt install graphviz
      - name: Generate JIG
        run: ./gradlew clean build jig
      - name: Deploy GithubPages
        run: |
          git config --global user.email "sammy@nocono.net"
          git config --global user.name "Abe Asami"
          git rm .gitignore
          mkdir ./build/jig/.circleci
          cp ./.circleci/config.yml ./build/jig/.circleci
          git add ./build/jig
          git commit -m "Update jig"
          git push origin `git subtree split --prefix build/jig ${GITHUB_REF#refs/heads/}`:gh-pages --force