on:
  push:
    branches: [ master, main, unit-test ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
#      - run: ./gradlew bootRun
#        env:
#          SPRING_DATASOURCE_URL: jdbc:postgresql:postgres
#          SPRING_DATASOURCE_USERNAME: postgres
#          SPRING_DATASOURCE_PASSWORD: secret
      - run: ./gradlew test --tests "library.e2e.*" --no-daemon
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql:postgres
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: secret
